### ISSUE TITLE
Support pre-commit compatibility for markdownlint-cli

### ISSUE THREAD

**Issue by siddjellali** [samchon/prisma-markdown#30]
Hello,

First of all, thank you for the great work on `markdownlint-cli`.

I would like to propose a small enhancement to improve compatibility with the [`pre-commit`](https://pre-commit.com/) framework. 
Currently, when integrating `markdownlint-cli` in a `.pre-commit-config.yaml` like the following:

```yaml
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.43.0
  hooks:
    - id: markdownlint
```
`pre-commit` throws an error

Thank you in advance for considering this enhancement.
